[versions]
spigot = "26.1.2-R0.1-SNAPSHOT"
papi = "2.12.2"
ess = "2.21.2"

[libraries]
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
papi = { group = "me.clip", name = "placeholderapi", version.ref = "papi" }
ess = { group = "net.essentialsx", name = "EssentialsX", version.ref = "ess" }